version: '3.5'
services:

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./postgres:/temp
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@localhost}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  sails:
    build:
      context: .
      dockerfile: ./sails-api/Dockerfile
    #environment:
       # check in directory config\env  
    #   NODE_ENV: staging40002
    #command: "pm2 start app.js --name='sails-skeleton-api-40002' --no-daemon"   
    ## development
    command: nodemon --ignore 'tmp/*' app.js && exit 0
    volumes:
      - ./sails-api:/app
      - /app/node_modules
    ports:
      - "8000:1337"
    networks:
      - postgres

  vue:
    build:
      context: .
      dockerfile: ./vue-admin/Dockerfile
    volumes:
      - ./vue-admin:/app
      - /app/node_modules
    ports:
      - "9000:8080"
    links:
      - postgres
  
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    
 